"""empty message

Revision ID: 0742fb271974
Revises: 179be61b8746
Create Date: 2024-12-03 11:08:03.208211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0742fb271974'
down_revision: Union[str, None] = '179be61b8746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tradingstrategy', 'total_profit')
    op.drop_column('tradingstrategy', 'available_profit')
    op.drop_column('tradingstrategy', 'realized_profit')
    op.drop_column('tradingstrategy', 'tax_reserve')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tradingstrategy', sa.Column('tax_reserve', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tradingstrategy', sa.Column('realized_profit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tradingstrategy', sa.Column('available_profit', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tradingstrategy', sa.Column('total_profit', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
