"""add_profit_columns

Revision ID: 9df8fd353aa7
Revises: 
Create Date: 2024-11-19 13:45:22.167040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9df8fd353aa7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.alter_column('status',
                            type_=sa.VARCHAR(12),
                            existing_type=sa.String(),
                            existing_nullable=True)
    op.add_column('tradingstrategy', sa.Column('total_profit', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='0'))
    op.add_column('tradingstrategy', sa.Column('realized_profit', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='0'))
    op.add_column('tradingstrategy', sa.Column('tax_reserve', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='0'))
    op.add_column('tradingstrategy', sa.Column('available_profit', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='0'))
    op.alter_column('tradingstrategy', 'type',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('RANGE', 'BREAKOUT', 'TAKE_PROFIT', name='strategytype'),
               existing_nullable=False)
    op.create_index(op.f('ix_tradingstrategy_name'), 'tradingstrategy', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tradingstrategy_name'), table_name='tradingstrategy')
    op.alter_column('tradingstrategy', 'type',
               existing_type=sa.Enum('RANGE', 'BREAKOUT', 'TAKE_PROFIT', name='strategytype'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.drop_column('tradingstrategy', 'available_profit')
    op.drop_column('tradingstrategy', 'tax_reserve')
    op.drop_column('tradingstrategy', 'realized_profit')
    op.drop_column('tradingstrategy', 'total_profit')
    op.alter_column('order', 'status',
               existing_type=sa.Enum('ACCEPTED', 'LIVE', 'CANCELLED', 'FILLED', 'PARTIAL_FILL', 'REJECTED', name='orderstate'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
