version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: gemini_bot
      POSTGRES_PASSWORD: gemini_bot_password
      POSTGRES_DB: gemini_bot
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gemini_bot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 